<project xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xmlns="http://maven.apache.org/POM/4.0.0"
  xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
  <artifactId>blossom-parent</artifactId>

  <dependencyManagement>
    <dependencies>
      <dependency>
        <artifactId>spring-boot-dependencies</artifactId>
        <groupId>org.springframework.boot</groupId>
        <scope>import</scope>
        <type>pom</type>
        <version>${springboot.version}</version>
      </dependency>

      <dependency>
        <artifactId>spring-plugin-core</artifactId>
        <groupId>org.springframework.plugin</groupId>
        <version>${spring.plugin.core.version}</version>
      </dependency>

      <dependency>
        <artifactId>jna</artifactId>
        <groupId>net.java.dev.jna</groupId>
        <version>${jna.version}</version>
      </dependency>

      <dependency>
        <artifactId>commons-lang3</artifactId>
        <groupId>org.apache.commons</groupId>
        <version>${commons-lang3.version}</version>
      </dependency>
      <dependency>
        <artifactId>bcprov-jdk18on</artifactId>
        <groupId>org.bouncycastle</groupId>
        <version>${bouncycastle.version}</version>
      </dependency>
      <dependency>
        <artifactId>bcmail-jdk18on</artifactId>
        <groupId>org.bouncycastle</groupId>
        <version>${bouncycastle.version}</version>
      </dependency>

      <dependency>
        <artifactId>camunda-bpm-spring-boot-starter-rest</artifactId>
        <groupId>org.camunda.bpm.springboot</groupId>
        <version>${camunda.version}</version>
      </dependency>
      <dependency>
        <artifactId>tika-core</artifactId>
        <groupId>org.apache.tika</groupId>
        <version>${tika.version}</version>
      </dependency>

      <dependency>
        <artifactId>guava</artifactId>
        <groupId>com.google.guava</groupId>
        <version>${guava.version}</version>
      </dependency>
      <dependency>
        <groupId>de.larsgrefer.sass</groupId>
        <artifactId>sass-embedded-host</artifactId>
        <version>${sass-embedded.version}</version>
      </dependency>
      <dependency>
        <groupId>commons-io</groupId>
        <artifactId>commons-io</artifactId>
        <version>${commons-io.version}</version>
      </dependency>
      <dependency>
        <artifactId>jakarta.annotation-api</artifactId>
        <groupId>jakarta.annotation</groupId>
        <version>${jakarta.annotation}</version>
      </dependency>
      <dependency>
        <artifactId>jakarta.validation-api</artifactId>
        <groupId>jakarta.validation</groupId>
        <version>${jakarta.validation}</version>
      </dependency>
      <dependency>
        <artifactId>elasticsearch</artifactId>
        <groupId>org.elasticsearch</groupId>
        <version>${elasticsearch.version}</version>
      </dependency>
      <dependency>
        <artifactId>transport</artifactId>
        <groupId>org.elasticsearch.client</groupId>
        <version>${elasticsearch.version}</version>
      </dependency>
      <dependency>
        <groupId>com.mailjet</groupId>
        <artifactId>mailjet-client</artifactId>
        <version>${mailjet.version}</version>
      </dependency>
      <dependency>
        <groupId>junit</groupId>
        <artifactId>junit</artifactId>
        <version>4.13.2</version>
        <scope>test</scope>
      </dependency>
      <dependency>
        <groupId>org.junit.vintage</groupId>
        <artifactId>junit-vintage-engine</artifactId>
        <version>5.11.4</version>
        <scope>test</scope>
      </dependency>
    </dependencies>
  </dependencyManagement>

  <modelVersion>4.0.0</modelVersion>
  <name>blossom-parent</name>

  <packaging>pom</packaging>
  <parent>
    <artifactId>blossom</artifactId>
    <groupId>com.blossom-project</groupId>
    <version>4.0.0-SNAPSHOT</version>
  </parent>

  <properties>
    <bouncycastle.version>1.80</bouncycastle.version>
    <camunda.version>7.22.0</camunda.version>
    <commons-lang3.version>3.17.0</commons-lang3.version>
    <guava.version>33.4.6-jre</guava.version>
    <jakarta.annotation>2.1.1</jakarta.annotation>
    <jakarta.validation>3.1.0</jakarta.validation>
    <jna.version>5.16.0</jna.version>
    <sass-embedded.version>4.4.0</sass-embedded.version>
    <liquibase.version>4.31.0</liquibase.version>
    <maven.compiler.source>21</maven.compiler.source>
    <maven.compiler.target>21</maven.compiler.target>
    <elasticsearch.version>7.17.7</elasticsearch.version>
    <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
    <querydsl.version>5.1.0</querydsl.version>
    <spring.plugin.core.version>3.0.0</spring.plugin.core.version>
    <springboot.version>4.0.0</springboot.version>
    <tika.version>3.2.0</tika.version>
    <commons-io.version>2.18.0</commons-io.version>
    <mailjet.version>5.2.6</mailjet.version>
  </properties>

  <url>http://maven.apache.org</url>

  <build>
    <pluginManagement>
      <plugins>
        <plugin>
          <groupId>org.codehaus.mojo</groupId>
          <artifactId>build-helper-maven-plugin</artifactId>
          <version>3.6.0</version>
          <executions>
            <execution>
              <id>add-querydsl-generated-sources</id>
              <phase>generate-sources</phase>
              <goals>
                <goal>add-source</goal>
              </goals>
              <configuration>
                <sources>
                  <source>${project.build.directory}/generated-sources</source>
                </sources>
              </configuration>
            </execution>
          </executions>
        </plugin>
      </plugins>
    </pluginManagement>
  </build>
</project>
