<project xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xmlns="http://maven.apache.org/POM/4.0.0"
  xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
  <artifactId>blossom-parent</artifactId>

  <dependencyManagement>
    <dependencies>
      <dependency>
        <artifactId>spring-boot-dependencies</artifactId>
        <groupId>org.springframework.boot</groupId>
        <scope>import</scope>
        <type>pom</type>
        <version>${springboot.version}</version>
      </dependency>

      <dependency>
        <artifactId>spring-plugin-core</artifactId>
        <groupId>org.springframework.plugin</groupId>
        <version>${spring.plugin.core.version}</version>
      </dependency>

      <dependency>
        <artifactId>jna</artifactId>
        <groupId>com.sun.jna</groupId>
        <version>${jna.version}</version>
      </dependency>

      <dependency>
        <artifactId>commons-lang3</artifactId>
        <groupId>org.apache.commons</groupId>
        <version>${commons-lang3.version}</version>
      </dependency>
      <dependency>
        <artifactId>bcprov-jdk15on</artifactId>
        <groupId>org.bouncycastle</groupId>
        <version>${bouncycastle.version}</version>
      </dependency>
      <dependency>
        <artifactId>bcmail-jdk15on</artifactId>
        <groupId>org.bouncycastle</groupId>
        <version>${bouncycastle.version}</version>
      </dependency>

      <dependency>
        <artifactId>camunda-bpm-spring-boot-starter-rest</artifactId>
        <groupId>org.camunda.bpm.springboot</groupId>
        <version>${camunda.version}</version>
      </dependency>
      <dependency>
        <artifactId>tika-core</artifactId>
        <groupId>org.apache.tika</groupId>
        <version>${tika.version}</version>
      </dependency>

      <dependency>
        <artifactId>guava</artifactId>
        <groupId>com.google.guava</groupId>
        <version>${guava.version}</version>
      </dependency>
      <dependency>
        <artifactId>powermock-module-junit4</artifactId>
        <groupId>org.powermock</groupId>
        <version>${powermock.version}</version>
      </dependency>
      <dependency>
        <artifactId>powermock-api-mockito2</artifactId>
        <groupId>org.powermock</groupId>
        <version>${powermock.version}</version>
      </dependency>
      <dependency>
        <artifactId>jsass</artifactId>
        <groupId>io.bit3</groupId>
        <version>${jsass.version}</version>
        <exclusions>
          <exclusion>
            <groupId>org.slf4j</groupId>
            <artifactId>slf4j-api</artifactId>
          </exclusion>
        </exclusions>
      </dependency>
      <dependency>
        <artifactId>jakarta.annotation-api</artifactId>
        <groupId>jakarta.annotation</groupId>
        <version>${jakarta.annotation}</version>
      </dependency>
      <dependency>
        <artifactId>jakarta.validation-api</artifactId>
        <groupId>jakarta.validation</groupId>
        <version>${jakarta.validation}</version>
      </dependency>
      <dependency>
        <artifactId>elasticsearch</artifactId>
        <groupId>org.elasticsearch</groupId>
        <version>${elasticsearch.version}</version>
      </dependency>
      <dependency>
        <artifactId>transport</artifactId>
        <groupId>org.elasticsearch.client</groupId>
        <version>${elasticsearch.version}</version>
      </dependency>
    </dependencies>
  </dependencyManagement>

  <modelVersion>4.0.0</modelVersion>
  <name>blossom-parent</name>

  <packaging>pom</packaging>
  <parent>
    <artifactId>blossom</artifactId>
    <groupId>com.blossom-project</groupId>
    <version>3.0.0-SNAPSHOT</version>
  </parent>

  <properties>
    <bouncycastle.version>1.62</bouncycastle.version>
    <camunda.version>3.2.0</camunda.version>
    <commons-lang3.version>3.7</commons-lang3.version>
    <guava.version>31.1-jre</guava.version>
    <jakarta.annotation>2.1.1</jakarta.annotation>
    <jakarta.validation>3.0.2</jakarta.validation>
    <jna.version>3.0.9</jna.version>
    <jsass.version>5.10.5</jsass.version>
    <liquibase.version>3.6.3</liquibase.version>
    <maven.compiler.source>17</maven.compiler.source>
    <maven.compiler.target>17</maven.compiler.target>
    <elasticsearch.version>7.17.7</elasticsearch.version>
    <powermock.version>2.0.2</powermock.version>
    <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
    <spring.plugin.core.version>3.0.0</spring.plugin.core.version>
    <springboot.version>3.0.0</springboot.version>
    <tika.version>1.22</tika.version>
  </properties>

  <url>http://maven.apache.org</url>
</project>
