<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
  <parent>
    <artifactId>blossom-autoconfigure</artifactId>
    <groupId>com.blossom-project</groupId>
    <version>2.0.0-SNAPSHOT</version>
  </parent>
  <modelVersion>4.0.0</modelVersion>

  <artifactId>autoconfigure-filemanager</artifactId>
  <dependencies>
    <dependency>
      <groupId>com.blossom-project</groupId>
      <artifactId>blossom-module-filemanager</artifactId>
      <version>2.0.0-SNAPSHOT</version>
      <optional>true</optional>
    </dependency>

    <!-- Generate spring-configuration-metadata.json on process -->
    <dependency>
      <groupId>org.springframework.boot</groupId>
      <artifactId>spring-boot-configuration-processor</artifactId>
      <optional>true</optional>
    </dependency>
  </dependencies>

</project>