blossom:
  security:
    default:
      account:
        password: system
        identifier: system
        enabled: true
  elasticsearch:
    cluster-name: someName
    cluster-nodes: someUrl
    enabled: "no"
spring:
  jpa:
    hibernate:
      ddl-auto: create

  liquibase:
    enabled: false
  elasticsearch:
    rest:
      uris: someUrl


management:
  health:
    elasticsearch:
      enabled: false
server:
  port: 8081
